spring.application.name=todolist
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:h2:mem:todolist
jwt.secret=lanclanoidoq82u00u20u01j01dj0jid01d01u20dj01jd012d10jd10j